# Generated by Django 4.2 on 2023-04-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='podcasts',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='podcast',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='file',
            field=models.FileField(null=True, upload_to='mp3_files/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='myapp.user'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
