# Generated by Django 4.2 on 2023-04-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_playlist_podcasts_remove_playlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='cover',
            field=models.FileField(null=True, upload_to='covers/'),
        ),
    ]
