# Generated by Django 4.2 on 2023-04-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='user',
            new_name='added_by',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
