# Generated by Django 4.2 on 2023-04-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_user_podcast_added_by_alter_podcast_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to='profiles_picture/'),
        ),
    ]
